#pragma once

#include "WoWWorldObject.h"

#include "World/Creature/Creature.h"

enum ZN_API CreatureType : uint32
{
	CREATURE_TYPE_BEAST = 1,
	CREATURE_TYPE_DRAGONKIN = 2,
	CREATURE_TYPE_DEMON = 3,
	CREATURE_TYPE_ELEMENTAL = 4,
	CREATURE_TYPE_GIANT = 5,
	CREATURE_TYPE_UNDEAD = 6,
	CREATURE_TYPE_HUMANOID = 7,
	CREATURE_TYPE_CRITTER = 8,
	CREATURE_TYPE_MECHANICAL = 9,
	CREATURE_TYPE_NOT_SPECIFIED = 10,
	CREATURE_TYPE_TOTEM = 11,
	CREATURE_TYPE_NON_COMBAT_PET = 12,
	CREATURE_TYPE_GAS_CLOUD = 13
};

enum ZN_API CreatureTypeFlags : uint32
{
	CREATURE_TYPEFLAGS_TAMEABLE = 0x0001,
	CREATURE_TYPEFLAGS_HERBLOOT = 0x0100,
	CREATURE_TYPEFLAGS_MININGLOOT = 0x0200
};

enum ZN_API CreatureFamily : uint32
{
	CREATURE_FAMILY_WOLF = 1,
	CREATURE_FAMILY_CAT = 2,
	CREATURE_FAMILY_SPIDER = 3,
	CREATURE_FAMILY_BEAR = 4,
	CREATURE_FAMILY_BOAR = 5,
	CREATURE_FAMILY_CROCOLISK = 6,
	CREATURE_FAMILY_CARRION_BIRD = 7,
	CREATURE_FAMILY_CRAB = 8,
	CREATURE_FAMILY_GORILLA = 9,
	CREATURE_FAMILY_RAPTOR = 11,
	CREATURE_FAMILY_TALLSTRIDER = 12,
	CREATURE_FAMILY_FELHUNTER = 15,
	CREATURE_FAMILY_VOIDWALKER = 16,
	CREATURE_FAMILY_SUCCUBUS = 17,
	CREATURE_FAMILY_DOOMGUARD = 19,
	CREATURE_FAMILY_SCORPID = 20,
	CREATURE_FAMILY_TURTLE = 21,
	CREATURE_FAMILY_IMP = 23,
	CREATURE_FAMILY_BAT = 24,
	CREATURE_FAMILY_HYENA = 25,
	CREATURE_FAMILY_OWL = 26,
	CREATURE_FAMILY_WIND_SERPENT = 27,
	// [TZERO] tbc enumerations [?]
	CREATURE_FAMILY_REMOTE_CONTROL = 28,
	CREATURE_FAMILY_FELGUARD = 29,
	CREATURE_FAMILY_DRAGONHAWK = 30,
	CREATURE_FAMILY_RAVAGER = 31,
	CREATURE_FAMILY_WARP_STALKER = 32,
	CREATURE_FAMILY_SPOREBAT = 33,
	CREATURE_FAMILY_NETHER_RAY = 34,
	CREATURE_FAMILY_SERPENT = 35,
	CREATURE_FAMILY_SEA_LION = 36
};

enum MoveFlags
{
	MOVEFLAG_NONE = 0x00000000,
	MOVEFLAG_SLIDE = 0x00000002,
	MOVEFLAG_MARCH_ON_SPOT = 0x00000004,
	MOVEFLAG_JUMP = 0x00000008,
	MOVEFLAG_WALK = 0x00000100,
	MOVEFLAG_FLY = 0x00000200,   //For dragon (+walk = glide)
	MOVEFLAG_ORIENTATION = 0x00000400,   //Fix orientation
};

enum MovementFlags
{
	MOVEMENTFLAG_FORWARD = 0x1,
	MOVEMENTFLAG_BACKWARD = 0x2,
	MOVEMENTFLAG_STRAFE_LEFT = 0x4,
	MOVEMENTFLAG_STRAFE_RIGHT = 0x8,
	MOVEMENTFLAG_LEFT = 0x10,
	MOVEMENTFLAG_RIGHT = 0x20,
	MOVEMENTFLAG_PITCH_UP = 0x40,
	MOVEMENTFLAG_PITCH_DOWN = 0x80,

	MOVEMENTFLAG_WALK_MODE = 0x100,
	MOVEMENTFLAG_JUMPING = 0x2000,
	MOVEMENTFLAG_FALLING = 0x4000,
	MOVEMENTFLAG_SWIMMING = 0x200000,
	MOVEMENTFLAG_ONTRANSPORT = 0x2000000,
	MOVEMENTFLAG_SPLINE = 0x4000000,

	//[TZERO] other enumeration to delete or check  
	MOVEMENTFLAG_NONE = 0x00000000,
	MOVEMENTFLAG_LEVITATING = 0x00000400,
	MOVEMENTFLAG_FLY_UNK1 = 0x00000800,
	MOVEMENTFLAG_UNK4 = 0x00002000,
	// 0x8000, 0x10000, 0x20000, 0x40000, 0x80000, 0x100000
	MOVEMENTFLAG_CAN_FLY = 0x00800000,
	MOVEMENTFLAG_SPLINE2 = 0x08000000,               // used for flight paths
	MOVEMENTFLAG_WATERWALKING = 0x10000000,               // prevent unit from falling through water
	MOVEMENTFLAG_SAFE_FALL = 0x20000000,               // active rogue safe fall spell (passive)
	MOVEMENTFLAG_UNK3 = 0x40000000
};

enum UnitDynFlags
{
	UNIT_DYNFLAG_LOOTABLE = 0x0001,
	UNIT_DYNFLAG_TRACK_UNIT = 0x0002,
	UNIT_DYNFLAG_OTHER_TAGGER = 0x0004,
	UNIT_DYNFLAG_ROOTED = 0x0008,
	UNIT_DYNFLAG_SPECIALINFO = 0x0010,
	UNIT_DYNFLAG_DEAD = 0x0020
};

class ZN_API WoWUnit
	: public WorldObject
{
public:
	WoWUnit();
	virtual ~WoWUnit();

	virtual void UpdateMovementData(CByteBuffer& Bytes) override; // For inheritance

public:
	static std::shared_ptr<WoWUnit> Create(IBaseManager& BaseManager, IRenderDevice& RenderDevice, IScene * Scene, uint64 guid);
	virtual void AfterCreate(IBaseManager& BaseManager, IRenderDevice& RenderDevice, IScene * Scene) override;

protected:
	uint32 flags2;
	float Speed_MOVE_WALK = 0.0f;
	float Speed_MOVE_RUN = 0.0f;
	float Speed_MOVE_SWIM_BACK = 0.0f;
	float Speed_MOVE_SWIM = 0.0f;
	float Speed_MOVE_RUN_BACK = 0.0f;
	float Speed_MOVE_TURN_RATE = 0.0f;

private:
	std::shared_ptr<Creature> m_HiddenNode;
};